---
- name: Deploy | Create Virtualenv Dir
  file:
    path: "{{ ansible_virtualenv_dir }}"
    recurse: yes

# There is no Ansible module to idempotently create virtualenvs
# `pip` does so just fine, `virtualenv` installs pip by default,
# so we use it as a dummy package here. It also guarantees that we have
# version 10.0+, which is required for some packages we want to use.
- name: Deploy | Create Ansible Virtualenv
  pip:
    virtualenv: "{{ ansible_virtualenv_dir }}"
    # Inherit system packages, the yum python bindings are necessary for CentOS
    # and cannot be installed from PyPI, as they have a native component.
    virtualenv_site_packages: yes
    name: pip>=10.0
